# @see https://github.com/DavidAnson/markdownlint
---
default: true
extends: null
fenced-code-language: false
line_length: false
no-bare-urls: false
no-inline-html: false
ol-prefix: false
ul-indent:
  indent: 2
ul-style:
  style: consistent
